### ISSUE TITLE
Improve Details Tab Scroll Behavior

### ISSUE THREAD

**Issue by PramUkesh** [KYHSGeekCode/Android-Disassembler#11]
While Scrolling Details of Disassembled file Scrolling lags

Improve This Behavior and add smoothness

**Comment by PramUkesh** [comment]
also rows option has Korean lang so convert to English or based on device language 
Not able to understood which is yes or no and also description below select rows to view in Korean change this also

**Comment by KYHSGeekCode** [comment]
Right. And I want to let you know some secrets of mere  decorations (not implemented): that "row select" option and "machine select(auto-detect, arm, armthumb, powerpc, etc...) Maybe I may use some better listview/tablelayout libs...

**Comment by PramUkesh** [comment]
> Korean lang

Also Think about this
