### ISSUE TITLE
Permission Dialog always showing

### ISSUE THREAD

**Issue by PramUkesh** [KYHSGeekCode/Android-Disassembler#12]
Show App permission dialog only for first time

**Comment by KYHSGeekCode** [comment]
In my phone it never shows  that to me.. (Sigh)

**Comment by PramUkesh** [comment]
since i was side loading the app i think app permissions automatically granted or
may be app is targeting minimum sdk version that doesn't require user interaction(means targeting sdk version 22) so permissions granted automatically

**Comment by PramUkesh** [comment]
> You mean AlertDialog that shows rationals

Yes

**Comment by KYHSGeekCode** [comment]
This should have been fixed from release 0.9.8.
