### ISSUE TITLE
Some Enhancements

### ISSUE THREAD

**Issue by PramUkesh** [KYHSGeekCode/Android-Disassembler#13]
1.Opening details tab or Disassemble tab without having file to decompile shows toast instead direct user to file selector activity to select file  
2.add option to stop decompile process if user wants to stop it there is no option for that

**Comment by KYHSGeekCode** [comment]
2 is what I was working on, and 1 is Very GOOD Idea.

**Comment by KYHSGeekCode** [comment]
Fixed in release 0.9.8.
