### ISSUE TITLE
What are these todos

### ISSUE THREAD

**Issue by PramUkesh** [KYHSGeekCode/Android-Disassembler#16]
Explain these
- add menus on clicking disassemblies.
- add coloring.

**Comment by KYHSGeekCode** [comment]
Coloring: highlight important instructions like jmp, call, syscall, int, cmp, ret, push, etc...
[Image](https://erichokanson.files.wordpress.com/2015/04/ollyviewmenu.png)

Menus in disassembly: on long-press a row, the popup menu asking what a user trying to do; e.g. on jump instruction, analyzing the destination, etc..
