### ISSUE TITLE
Directly Open from File Manager App

### ISSUE THREAD

**Issue by PramUkesh** [KYHSGeekCode/Android-Disassembler#17]
This is enhancement like
When we want to open MP3 files we don't have to go to music player instead we can open from File Manager App in our phone likewise
Add an ability to open files from file manager to decompile so that we don't have to open app to decompile so this reduces time consumption

**Comment by KYHSGeekCode** [comment]
Good idea.

**Comment by KYHSGeekCode** [comment]
Dev finished and will be applied in 1.0.0.
