### ISSUE TITLE
Go to Last Browsed folder

### ISSUE THREAD

**Issue by PramUkesh** [KYHSGeekCode/Android-Disassembler#18]
When we click select file it shows storage option selection choose files instead of browsing always from start add an option to go to last browsed folder directly because
if file lies in /0/Folder/folder/folder/../file.so
we have to always go to such deep folder to select file so add feature to go to last accessed folder
also some people saves binary files in same folder or at least android system does it saves most of the files in same system folder so it can be useful if add root functionality to the app

**Comment by KYHSGeekCode** [comment]
@PramUkesh I managed to solve this and now it works! This will be applied in v1.4.5.
