### ISSUE TITLE
Save project pop-up

### ISSUE THREAD

**Issue by mscalindt** [KYHSGeekCode/Android-Disassembler#31]
Tapping back right after launching the app will always display "Save Project" dialogue.

**Comment by KYHSGeekCode** [comment]
Oh, I may have to fix that. But I don't know when I can fix that. (D-17 of an important exam(CSAT))  Pull request is welcomed, or I may fix it some day. Thanks!

**Comment by KYHSGeekCode** [comment]
Will be fixed in next release.
