### ISSUE TITLE
Add root file browser

### ISSUE THREAD

**Issue by mscalindt** [KYHSGeekCode/Android-Disassembler#32]
Would be nice to have the ability to pick from "/" folder instead of Internal Storage.

**Comment by KYHSGeekCode** [comment]
> Hi, this feature is already under development for 3.0 in dev-3.0 branch and will be released by 1st December.
 > 
 > Thanks for the suggestion, if you have any other suggestion please feel free to open an issue here

-By codeKidX

**Comment by KYHSGeekCode** [comment]
Hooray! @mscalindt
