### ISSUE TITLE
error: cannot find symbol class PLT

### ISSUE THREAD

**Issue by kakopappa** [KYHSGeekCode/Android-Disassembler#41]
I am trying to build the project with Android Studio 3. 

I am getting  

> error: cannot find symbol class PLT 

I cannot find the class name PLT in the code as well. Plus JNI functions for

public static native String Demangle(String mangled);
public static native List<PLT> ParsePLT(String filepath);

seems to be missing as well. 

Is the code upto date in github?

**Comment by KYHSGeekCode** [comment]
> I am trying to build the project with Android Studio 3.
> 
> I am getting
> 
>     error: cannot find symbol class PLT
> 
> I cannot find the class name PLT in the code as well. 

Thanks!
I think that PLT.jjava was omitted when I git pushed.

The JNI part is in jnilib/libhellojni.so.

The hello-jni.cpp is up to date.

**Comment by KYHSGeekCode** [comment]
+ParsePLT is not used by now, because I don't know how to use PLTHook Library, so I'm gonna parse by myself.
