### ISSUE TITLE
when will the updated version will release?

### ISSUE THREAD

**Issue by rubysm** [KYHSGeekCode/Android-Disassembler#75]
And you can update in playstore also!

**Comment by KYHSGeekCode** [comment]
I will try to release the next release before this month ends..!

**Comment by KYHSGeekCode** [comment]
I actually released my 1.6.1 pre-release binary on github, but I am having trouble release-building.

**Comment by KYHSGeekCode** [comment]
It seems hard for me to update my app before this year ends :( hew hew..
I am currently drown in my spaghetti codes.. haha

**Comment by KYHSGeekCode** [comment]
I am working to publish a new version before February ends!
